### ISSUE TITLE
Ability to rewire prev results to current task args

### ISSUE THREAD

**Issue by foo123** [chaoran/node-serialize#1]
Hi,

your lib is just what i was looking for for some tools i have.
It is so simple, it is brilliant.

However a small addition is needed:
Scenario:

``` javascript

var fs = require('fs');
var serialize = require('./utils/node-serialize');

fs.writeFile = serialize(fs.writeFile);
fs.readFile = serialize(fs.readFile);

fs.writeFile('./foo1.txt', 'test1', { encoding: 'utf8'});
fs.readFile('./foo1.txt', { encoding: 'utf8'});
// i would like to replace the 1st arg with the data read in previous step
fs.writeFile('./foo2.txt', 'this arg should be replaced with test1', { encoding: 'utf8'});

// foo2.txt content is  'this arg should be replaced with test1' instead of 'test1'

```

i made a small extension in the lib to be able to rewire previous results to current task args:

``` javascript

var fs = require('fs');
var serialize = require('./utils/node-serialize');

fs.writeFile = serialize(fs.writeFile);
fs.readFile = serialize(fs.readFile);

fs.writeFile('./foo1.txt', 'test1', { encoding: 'utf8'});
// rewire the results[1] to the next task's args[1], multiple rewires can be added in same call
fs.readFile('./foo1.txt', { encoding: 'utf8'}).rewire([1, 1]);
// i would like to replace the 1st arg with the data read in previous step
fs.writeFile('./foo2.txt', 'this arg should be replaced with test1', { encoding: 'utf8'});

// foo2.txt content is  now correctly  'test1'

```

extended code:

``` javascript
var slice = Array.prototype.slice;
var queues = [];
var _prevResult = null;
var _currentRewire = null;

var WorkQueue = function() {
  this.running = null;
  this.pending = [];
};

WorkQueue.get = function(name) {
  var queue = queues[name];
  if (!queue) queue = queues[name] = new WorkQueue();
  return queue;
};

WorkQueue.prototype.add = function(_this, func, args, noCallback, rewireArgs) {
  var that = this;

  if (noCallback) 
  {
    args.push(function(err) { 
        _prevResult = slice.call(arguments);
        _currentRewire = rewireArgs.rewire || null;
        that.next(err) 
    });
  } 
  else 
  {
    callback = args.pop();
    args.push(function() {
      callback.apply(this, arguments);
        _prevResult = slice.call(arguments);
        _currentRewire = rewireArgs.rewire || null;
      that.next(arguments[0]);
    });
  }

  var task = function(err) { 
    if (err instanceof Error) 
    {
        args[args.length - 1].call(global, err);
    }
    else 
    {
        console.log(["args before", args]);
        console.log(["rewire", _currentRewire]);
        if (_currentRewire && _prevResult)
        {
            // rewire prev results to current task args
            for (var i=0; i<_currentRewire.length; i++)
                args[_currentRewire[i][0]] = _prevResult[_currentRewire[i][1]];
        }
        _prevResult = null;
        console.log(["args after", args]);
        func.apply(_this, args);
    }
  };

  if (!this.running) (this.running = task)();
  else this.pending.push(task);
};

WorkQueue.prototype.next = function(err) {
  var run = this.running = this.pending.shift();
  if (run) run(err);
};

var serialize = function(func, name) {
  if (!name) name = 'default';

  var queue = WorkQueue.get(name)
    , length = func.length;

  var rewireArgs = { rewire: null };
  var serialized = function() {
    queue.add(this, func, slice.call(arguments), arguments.length < length, rewireArgs);
    return serialized;
  };

  serialized.rewire = function() { 
    var args = slice.call(arguments);
    if (args.length) rewireArgs.rewire = args;
    return serialized; 
};
  serialized.free = function() { return func; };
  return serialized;
}

module.exports = serialize;

```

i can make a pull request if everything is ok.

Nikos

**Comment by chaoran** [comment]
@foo123 Thanks for being interested in my little library. And thank you for putting effort in extending it.

Adding the ability to "rewire" results from a previous serialized call to the next serialized call is something I have carefully considered adding to **serialize** but yet to come up with a perfect plan. My main concern is **Compatibility with other libraries**. Serialize is easier to use mostly because it is safe to directly serialize library calls without affecting other libraries which also depend on the same call. For example, if you do `fs.readFile = serialize(fs.readFile);`, you modified the `readFile` function in `fs`. However, this modification is safe because it doesn't change the behavior of `readFile`; it just makes two `readFile` instances cannot run concurrently, which is `safer` than the original version. Because since it is safe to run `readFile` concurrently, it must be safe to run them one after another.

By adding the **rewire** ability, this guarantee is somewhat broken. For instance, if the code is

```
fs.readFile('./foo1.txt', { encoding: 'utf8'}).rewire([1, 1]); 
thirdpartycall(); 
fs.writeFile('./foo2.txt', 'this arg should be replaced with test1', { encoding: 'utf8'});
```

If the `thirdpartycall()` also calls `fs.writeFile`, the data you read from `./foo1.txt` will be rewired to the wrong file.

If you could propose a plan that solves the compatibility issue, I would be very happy to include your contribution.

Generally, if you want to pass data between asynchronous calls, use **callbacks**. Even if you are using serialize, you can still use callback functions to connect two asynchronous calls. For example, you can do:

```
fs.writeFile = serialize(fs.writeFile);
fs.readFile = serialize(fs.readFile);

fs.writeFile('./foo1.txt', 'test1', { encoding: 'utf8'});
fs.readFile('./foo1.txt', { encoding: 'utf8'}, function(err, data) {
  fs.writeFile('./foo2.txt', data, { encoding: 'utf8'});
});
```

**Comment by foo123** [comment]
Good point, the rational is that, adding callbacks actually beats the purpose of the whole serialize lib,

since in the example i posted in the first message, you are back to callback hell,

however, you dont need to overwrite the fs.readFile or fs.writeFile,

you can do 
var myserializedread = serialize(fs.readFile); // etc..

also the rewire method is supposed to work only for the current and next call, it should be re-called
if further rewire is needed in another step (this is not in the example i provided, but this is the idea) 

(this can be acieved by re-setting the task.rewireArgs.rewire to null after the task has been called )

Anyway, i was in the process of creatinfg a similar lib when i came accross yours, if you do not like this extension,

do you have a problem if i create a fork and add it myself, the rest of the code being the same as yours??

**Comment by foo123** [comment]
The idea behind this addition is that i am extending a custom build framework which will call an unknown number of exec commands (i dont want to depend on execSync extension)  (specified by user) and this makes the whole process very easy and intuitive to handle this functionality
iteratively, since each next command will use results from previous, and adding callbacks with unknown number of steps (although do-able) is a hell of mix-up and maintenance

**Comment by chaoran** [comment]
@foo123 If the number of exec commands is known when the function is called, then you can easily use Async.waterfall (https://github.com/caolan/async#waterfalltasks-callback) to achieve that.

If the number of exec commands will grow while each command is being executed, you had to implement it as a recursive call anyway, which would be make using callbacks very straight-forward.

Anyway, I'm not saying it's not useful to add the 'rewire'. It's very useful. It's just not the ideal plan. I want to make sure it is the best plan that I can come up with before publishing it.

**Comment by foo123** [comment]
ok no problem, probably i will create a custom lib, however i still like the serialized idea, was trying to wrap my mind around such an idea and i found this lib.

i still think, it is so simple it is brilliant.

**Comment by foo123** [comment]
added a custom fork here:

https://github.com/foo123/serializer

feel free to contact if anything needed
